name: 'coverage'
on:
  pull_request:
    branches:
      - master
      - main
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
  coverage:
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          coverage-file: report.json
          annotations: none